export const EDITOR_PAGE_DEFAULT_PADDING_VALUE = 50
export const DEFAULT_BACKGROUND_COLOR = '#f5f5f5'
export const DEFAULT_ACTIVE_SELECTION_LINT_WIDTH = 10
export const DEFAULT_ACTIVE_SELECTION_CORNER_WIDTH = 6
export const DEFAULT_ACTIVE_SELECTION_CORNER_HEIGHT = 6
